name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

env:
  IMAGE_VERSION: latest

jobs:
  pack:
    # if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: docker build
        env: 
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t z627062293/kubecit-service:$IMAGE_TAG -f ./Dockerfile .
          docker push z627062293/kubecit-service:$IMAGE_TAG
